[tool.poetry]
name = "tensorrt"
version = "0.1.0"
description = ""
authors = ["TensorRT [svc_tensorrt@nvidia.com]"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
wheel = "0.45.1"
setuptools = "^80.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
